In [28]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
df1 = pd.DataFrame(scores,columns=['國文','英文','數學','地理','探索'])
df1

     國文  英文  數學   地理   探索
0    51  82  93   70   55
1    55  57  81   91   77
2    95  51  85   79   67
3    85  83  52   73   95
4    74  67  66   59   87
5    97  50  96   58   76
6    71  95  70   72   87
7    63  87  81   62   97
8    81  58  62   91   73
9    78  63  85   97   70
10   92  77  87   84   50
11   60  83  97   64   65
12   87  71  73   73   89
13   93  50  64   80   88
14   61  77  63   86   99
15   77  94  87   77  100
16  100  80  63   86   79
17   76  59  90   67   95
18  100  81  89   96   92
19   68  87  62   58   84
20   65  84  90   63   62
21   70  51  88   80   55
22   94  99  81   84   78
23   69  62  66   84   92
24   91  82  80   96   61
25   94  56  91   71   92
26   53  72  76   51   59
27   50  78  61   72   81
28   55  57  86   70  100
29   77  66  77   68   72
30   65  63  52   58   85
31   89  98  98   63   64
32   97  53  80   94   59
33   54  89  59   96   61
34   89  57  70   72   71
35   64  51  70   93   52
36   97  91  82   58   51
37   54  74  63   62   83
38   66  83  73   60   74
39   97  89  71   67   84
40   93  60  64   80   65
41   61  68  91   56   52
42   96  86  59   70   74
43   78  57  88   86   83
44   59  65  78   56   79
45   63  76  65   93   84
46   65  59  63   70   87
47   85  80  82   80   81
48   64  71  83   72   82
49   62  54  73  100   66

In [35]:
import random
with open('names.txt',encoding='utf-8') as file:
    names_str = file.read()
    display(names_str)
names_list = names_str.split(sep='\n')
names = random.choices(names_list,k=50)

FileNotFoundError: [Errno 2] No such file or directory: 'names.txt'

In [36]:
#to_numpy()
df1.to_numpy()

array([[ 51,  82,  93,  70,  55],
       [ 55,  57,  81,  91,  77],
       [ 95,  51,  85,  79,  67],
       [ 85,  83,  52,  73,  95],
       [ 74,  67,  66,  59,  87],
       [ 97,  50,  96,  58,  76],
       [ 71,  95,  70,  72,  87],
       [ 63,  87,  81,  62,  97],
       [ 81,  58,  62,  91,  73],
       [ 78,  63,  85,  97,  70],
       [ 92,  77,  87,  84,  50],
       [ 60,  83,  97,  64,  65],
       [ 87,  71,  73,  73,  89],
       [ 93,  50,  64,  80,  88],
       [ 61,  77,  63,  86,  99],
       [ 77,  94,  87,  77, 100],
       [100,  80,  63,  86,  79],
       [ 76,  59,  90,  67,  95],
       [100,  81,  89,  96,  92],
       [ 68,  87,  62,  58,  84],
       [ 65,  84,  90,  63,  62],
       [ 70,  51,  88,  80,  55],
       [ 94,  99,  81,  84,  78],
       [ 69,  62,  66,  84,  92],
       [ 91,  82,  80,  96,  61],
       [ 94,  56,  91,  71,  92],
       [ 53,  72,  76,  51,  59],
       [ 50,  78,  61,  72,  81],
       [ 55,  57,  86,  70, 100],
       [ 77,  66,  77,  68,  72],
       [ 65,  63,  52,  58,  85],
       [ 89,  98,  98,  63,  64],
       [ 97,  53,  80,  94,  59],
       [ 54,  89,  59,  96,  61],
       [ 89,  57,  70,  72,  71],
       [ 64,  51,  70,  93,  52],
       [ 97,  91,  82,  58,  51],
       [ 54,  74,  63,  62,  83],
       [ 66,  83,  73,  60,  74],
       [ 97,  89,  71,  67,  84],
       [ 93,  60,  64,  80,  65],
       [ 61,  68,  91,  56,  52],
       [ 96,  86,  59,  70,  74],
       [ 78,  57,  88,  86,  83],
       [ 59,  65,  78,  56,  79],
       [ 63,  76,  65,  93,  84],
       [ 65,  59,  63,  70,  87],
       [ 85,  80,  82,  80,  81],
       [ 64,  71,  83,  72,  82],
       [ 62,  54,  73, 100,  66]])

In [37]:

#to_csv()
df1.to_csv('students.csv')

In [111]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
df1 = pd.DataFrame(scores,
                   columns=['國文','英文','數學','地理','探索'],
                   index=names)
df1

NameError: name 'names' is not defined

In [89]:
#to_numpy()
df1.to_numpy()

array([[ 51,  82,  93,  70,  55],
       [ 55,  57,  81,  91,  77],
       [ 95,  51,  85,  79,  67],
       [ 85,  83,  52,  73,  95],
       [ 74,  67,  66,  59,  87],
       [ 97,  50,  96,  58,  76],
       [ 71,  95,  70,  72,  87],
       [ 63,  87,  81,  62,  97],
       [ 81,  58,  62,  91,  73],
       [ 78,  63,  85,  97,  70],
       [ 92,  77,  87,  84,  50],
       [ 60,  83,  97,  64,  65],
       [ 87,  71,  73,  73,  89],
       [ 93,  50,  64,  80,  88],
       [ 61,  77,  63,  86,  99],
       [ 77,  94,  87,  77, 100],
       [100,  80,  63,  86,  79],
       [ 76,  59,  90,  67,  95],
       [100,  81,  89,  96,  92],
       [ 68,  87,  62,  58,  84],
       [ 65,  84,  90,  63,  62],
       [ 70,  51,  88,  80,  55],
       [ 94,  99,  81,  84,  78],
       [ 69,  62,  66,  84,  92],
       [ 91,  82,  80,  96,  61],
       [ 94,  56,  91,  71,  92],
       [ 53,  72,  76,  51,  59],
       [ 50,  78,  61,  72,  81],
       [ 55,  57,  86,  70, 100],
       [ 77,  66,  77,  68,  72],
       [ 65,  63,  52,  58,  85],
       [ 89,  98,  98,  63,  64],
       [ 97,  53,  80,  94,  59],
       [ 54,  89,  59,  96,  61],
       [ 89,  57,  70,  72,  71],
       [ 64,  51,  70,  93,  52],
       [ 97,  91,  82,  58,  51],
       [ 54,  74,  63,  62,  83],
       [ 66,  83,  73,  60,  74],
       [ 97,  89,  71,  67,  84],
       [ 93,  60,  64,  80,  65],
       [ 61,  68,  91,  56,  52],
       [ 96,  86,  59,  70,  74],
       [ 78,  57,  88,  86,  83],
       [ 59,  65,  78,  56,  79],
       [ 63,  76,  65,  93,  84],
       [ 65,  59,  63,  70,  87],
       [ 85,  80,  82,  80,  81],
       [ 64,  71,  83,  72,  82],
       [ 62,  54,  73, 100,  66]])

In [71]:
#to_csv()
df1.to_csv('students.csv')

In [76]:

#to_excel()
df1.to_excel('students.xlsx',sheet_name='3年5班')

ModuleNotFoundError: No module named 'openpyxl'